CREATE OR REPLACE PROCEDURE SCHEMA.SP_ERROR_HANDLE (IN I_PARAM VARCHAR(20))
    SPECIFIC SCHEMA.SP_ERROR_HANDLE
    RESULT SETS 1
    READS SQL DATA
    NOT DETERMINISTIC
    NULL CALL
    LANGUAGE SQL EXTERNAL ACTION
    INHERIT SPECIAL REGISTERS
BEGIN
  DECLARE v_RECORD_COUNT INTEGER;
  select count(*) INTO v_RECORD_COUNT from schema.MY_TABLE_STATUS where PARAM = I_PARAM;
  -- error handling
  if v_RECORD_COUNT = 0 then
    SIGNAL SQLSTATE '75002'
    SET MESSAGE_TEXT = 'record count should not be zero';
  end if;

  DECLARE c1 CURSOR WITH RETURN TO CLIENT FOR
  select * from SCHEMA.table1 where param1 = I_PARAM;

  OPEN c1;
END