-fno-default-inline             # do not make member functions inline by default
-fno-inline                     # do not expand any functions inline
-finline-functions              # Consider all functions for inlining, even if they are not declared inline. Enabled at level ‘-O3’.
